version: "3.8"
services:
  resumes_db:
    image: "mongo:3.6.8"
    ports:
      - 27017:27017
    volumes:
      - "/root/database/mongodb:/data/db"
    networks:
      - resumes_net
  resumes_web:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_USER: "owlman"
      DB_PWD: "41x0d40d7xfc5d2cxx"
    networks:
      - resumes_net
    links:
      - resumes_db:resumes_db
networks:
  resumes_net:
volumes:
  mongodb:
